### ISSUE TITLE
How to properly import Python google.cloud.language SDK?

### ISSUE THREAD

**Issue by mmz15** [googleapis/python-language#228]
I'm trying to implement entity sentiment analysis using Google's Natural Language API:

```
from google.cloud import language

client = language.LanguageServiceClient.from_service_account_json('credentials.json')
document = language.types.Document(
    content='Mona said that jogging is very fun.',
    type='PLAIN_TEXT')
```

However, I get the following error:
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/proto/message.py", line 457, in __init__
    pb_type = self._meta.fields[key].pb_type
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/proto/message.py", line 462, in __init__
    raise ValueError(
ValueError: Unknown field for Document: type
```

**How can I solve this error?** I've tried `from google.cloud import language_v1 as language` to no avail. For reference, `google-cloud==0.34.0`.

**Comment by parthea** [comment]
Hi @mmz15,

Please install `google-cloud-language` using `pip install `google-cloud-language`. If you already have it installed, please could you check the version of `google-cloud-language` using [these steps](https://github.com/googleapis/python-language/issues/new?assignees=&labels=&template=bug_report.md)?

**Comment by mmz15** [comment]
Sure:

#### Environment details

  - OS type and version: macOS Monterey
  - Python version: `Python 3.8.5`
  - pip version: `pip 20.2.4`
  - `google-cloud-language` version: 2.3.1
