### ISSUE TITLE
Error: gRPC error on request if code executed by Gunicorn

### ISSUE THREAD

**Issue by riZZZhik** [googleapis/python-language#309]
Hello,

Getting an error when using `google.oauth2.service_account.LanguageServiceClient` in Flask application executed by Gunicorn

### Environment details

  - Docker image: python:3.10.4
  - Python version: 3.10
  - pip version: 22.0.4
  - `google-cloud-language` version: 2.4.1

### Steps to reproduce

  1. Run code using Gunicorn: https://github.com/rizzzhik/belinsky/blob/feature/gcloud_nlp/docker-compose.yaml

### Code example

1) Repository: https://github.com/rizzzhik/belinsky/tree/feature/gcloud_nlp
2) Actual usage: https://github.com/riZZZhik/belinsky/blob/feature/gcloud_nlp/app/belinsky/routes/text_analyzer/text_analyzer.py

#### Without gRPC environments:
Code freezes on [`self.client.classify_text(document=document)`](https://github.com/riZZZhik/belinsky/blob/93adfb1d2c123f933c269733fae61197ca556a52/app/belinsky/routes/text_analyzer/text_analyzer.py#L29)

#### With gRPC environments:
```shell
# Due to: https://github.com/grpc/grpc/blob/master/doc/fork_support.md
export GRPC_ENABLE_FORK_SUPPORT=true
export GRPC_POLL_STRATEGY=poll
```

Trace:
```python
belinsky_app       | Traceback (most recent call last):
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
belinsky_app       |     response = self.full_dispatch_request()
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
belinsky_app       |     rv = self.handle_user_exception(e)
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
belinsky_app       |     rv = self.dispatch_request()
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
belinsky_app       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
belinsky_app       |   File "<decorator-gen-6>", line 2, in text_analyzer
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/prometheus_client/context_managers.py", line 81, in wrapped
belinsky_app       |     return func(*args, **kwargs)
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 277, in decorated_view
belinsky_app       |     return current_app.ensure_sync(func)(*args, **kwargs)
belinsky_app       |   File "/belinsky/belinsky/routes/text_analyzer/__init__.py", line 45, in text_analyzer
belinsky_app       |     analyzis = getattr(text_analyzer_worker, analyzis_type)(text)
belinsky_app       |   File "/belinsky/belinsky/routes/text_analyzer/text_analyzer.py", line 30, in classify_text
belinsky_app       |     return self.client.classify_text(document=document)
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/google/cloud/language_v1/services/language_service/client.py", line 852, in classify_text
belinsky_app       |     response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
belinsky_app       |     return wrapped_func(*args, **kwargs)
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
belinsky_app       |     return retry_target(
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
belinsky_app       |     return target()
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
belinsky_app       |     return callable_(*args, **kwargs)
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/grpc/_channel.py", line 944, in __call__
belinsky_app       |     state, call, = self._blocking(request, timeout, metadata, credentials,
belinsky_app       |   File "/usr/local/lib/python3.10/site-packages/grpc/_channel.py", line 926, in _blocking
belinsky_app       |     call = self._channel.segregated_call(
belinsky_app       |   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 498, in grpc._cython.cygrpc.Channel.segregated_call
belinsky_app       |   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 353, in grpc._cython.cygrpc._segregated_call
belinsky_app       |   File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 357, in grpc._cython.cygrpc._segregated_call
belinsky_app       | ValueError: Cannot invoke RPC on closed channel!
```

**Comment by riZZZhik** [comment]
Tips:
1) [Multiprocessing realisation from gRPC](https://github.com/grpc/grpc/tree/master/examples/python/multiprocessing)
2) Relevant issues:
    1) https://github.com/grpc/grpc/issues/24260
    2) https://github.com/grpc/grpc/issues/23317

**Comment by riZZZhik** [comment]
Also tried to do https://github.com/grpc/grpc/pull/14561, but it didn't help

**Comment by riZZZhik** [comment]
On fresh morning somehow fixed with [`GRPC_POLL_STRATEGY: poll`](https://github.com/riZZZhik/belinsky/commit/0d5b716c09a18dc36e04129bb2df82ea7ad407a3) environment.

But I guess it requires some investigation.
